services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: api-artist
    ports:
      - "12064:12064"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=monMotDePasseSuperSecret
      - SERVER_PORT=12064

volumes:
  db_data: