services:

  # ─── DATABASES ───────────────────────────────────────────────

  artistdb:
    image: mariadb:11.6.2-ubi9
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "db_artist:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmonMotDePasseSuperSecret"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

  userdb:
    image: mariadb:11.6.2-ubi9
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "db_user:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmonMotDePasseSuperSecret"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

  # ─── APIS (extrait) ──────────────────────────────────────────

  api-user:
    image: gitlab-depinfo-2025.univ-brest.fr:5050/e22101168/apis/api-user:v1.0.0
    ports:
      - "12063:8080"
    depends_on:
      userdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://userdb:3306/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=monMotDePasseSuperSecret

  api-artist:
    image: gitlab-depinfo-2025.univ-brest.fr:5050/e22101168/apis/api-artist:v1.0.0
    ports:
      - "12064:12064"
    depends_on:
      artistdb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://artistdb:3306/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=monMotDePasseSuperSecret
      - SERVER_PORT=12064

  api-scrapping:
    build: ./api-scrapping
    container_name: api-scrapping
    ports:
      - "12062:12062"

  # ─── GATEWAY ─────────────────────────────────────────────────

  gateway:
    build: ./gateaway
    container_name: gateway
    ports:
      - "12061:12061"
    depends_on:
      - api-artist
      - api-user
      - api-scrapping

volumes:
  db_artist:
  db_user: