services:
  mariadb:
    image: mariadb:11.6.2-ubi9
    container_name: api_gateway_db
    restart: unless-stopped
    volumes:
      - db_gateway:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmonMotDePasseSuperSecret"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_gateway: