services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: monMotDePasseSuperSecret
      MARIADB_DATABASE: test
    volumes:
      - db_data:/var/lib/mysql # On utilise un volume nommé ici
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: user-api-app
    ports:
      - "12063:12063" # Format : Hôte:Conteneur
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=monMotDePasseSuperSecret
      - SERVER_PORT=12063

volumes: # Ajoute ces deux lignes à la fin du fichier
  db_data: